before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  variables:
    VERSION: '0'
  stage: build
  script:
  - nuget restore
  - msbuild /t:restore
  - msbuild /property:Configuration=Release
  - $env:VERSION = (Get-Item $env:CI_PROJECT_DIR\SpeckleGSAUI\bin\Release\SpeckleGSA.dll).VersionInfo.FileVersion
  artifacts:
    name: "SpeckleGSA-${VERSION}"
    paths:
    - ${CI_PROJECT_DIR}\SpeckleGSAUI\bin\Release\*
    expire_in: 6 mos 