remote_theme: "mmistakes/minimal-mistakes@4.20.1"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: SpeckleGSA
description: Speckle plugin for Oasys GSA

include: 
  - _pages
  - _posts

plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style